server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: CAM-SERVICE
          uri: lb://CAM-SERVICE
          predicates:
            - Path=/cam/**
        - id: XNC-SERVICE
          uri: lb://XNC-SERVICE
          predicates:
            - Path=/XNC/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost